"""Regenerate the DeenSubs logo assets from the Illustrator export.

Input:  src/artifacts/deensubs-src.svg  (Illustrator export; "deensubs" is live
        <text> in Cairo SemiBold — everything else is already outlined)
Output: src/artifacts/deensubs.svg      (standalone, fully outlined, brand colors)
        src/components/logo.js          (LOGO_SVG theme-aware inline + FAVICON_SVG)

Usage:
    python3 -m venv venv && ./venv/bin/pip install fonttools uharfbuzz brotli
    ./venv/bin/python tools/logo/build-logo.py

The Cairo variable font is downloaded to tools/logo/ on first run.
"""
import json
import os
import re
import urllib.request

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
SRC = os.path.join(ROOT, "src", "artifacts", "deensubs-src.svg")
OUT_SVG = os.path.join(ROOT, "src", "artifacts", "deensubs.svg")
OUT_JS = os.path.join(ROOT, "src", "components", "logo.js")
FONT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cairo-var.ttf")
FONT_URL = "https://github.com/google/fonts/raw/main/ofl/cairo/Cairo%5Bslnt%2Cwght%5D.ttf"

TEXT, SIZE, ORIGIN = "deensubs", 80.0, (58.04, 203.21)  # match Illustrator layout
TEAL = "#0e6b63"
VB = "54 22 608 306"  # tight viewBox around the lockup


def outline_text():
    """Shape TEXT in Cairo SemiBold (wght 600) and return an SVG path d."""
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.misc.transform import Transform
    import uharfbuzz as hb

    if not os.path.exists(FONT):
        print("downloading Cairo variable font...")
        urllib.request.urlretrieve(FONT_URL, FONT)

    font = TTFont(FONT)
    instantiateVariableFont(font, {"wght": 600, "slnt": 0}, inplace=True)
    inst = FONT.replace(".ttf", "-600.ttf")
    font.save(inst)

    face = hb.Face(hb.Blob.from_file_path(inst))
    hbfont = hb.Font(face)
    hbfont.scale = (face.upem, face.upem)
    buf = hb.Buffer()
    buf.add_str(TEXT)
    buf.guess_segment_properties()
    hb.shape(hbfont, buf)

    glyphset = font.getGlyphSet()
    order = font.getGlyphOrder()
    scale = SIZE / face.upem
    paths, x = [], 0.0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        t = Transform().translate(ORIGIN[0] + (x + pos.x_offset) * scale,
                                  ORIGIN[1] - pos.y_offset * scale).scale(scale, -scale)
        pen = SVGPathPen(glyphset)
        glyphset[order[info.codepoint]].draw(TransformPen(pen, t))
        if pen.getCommands():
            paths.append(pen.getCommands())
        x += pos.x_advance
    d = " ".join(paths)
    d = re.sub(r"-?\d+\.\d+", lambda m: ("%.1f" % float(m.group())).rstrip("0").rstrip("."), d)
    return re.sub(r"\s+", " ", d).strip()


def main():
    src = open(SRC).read()
    text_d = outline_text()

    bubble = re.search(r'<path id="text_bubble"[^>]*d="([^"]+)"', src).group(1)
    bars = re.findall(r'<rect id="subtitle_[^"]+"[^>]*?x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)" rx="([^"]+)"', src)
    layer4 = re.search(r'<g id="Layer_4"[^>]*>(.*?)</g>', src, re.S).group(1)
    dots = re.findall(r'<rect class="cls-2" x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"/>', layer4)
    letters = re.findall(r'<(path|rect|polygon)(?! class)\s([^/]+)/>', layer4)

    def rects(items, fill):
        return "".join(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{fill}"/>' for x, y, w, h, *_ in items)

    def bar_rects(fill):
        return "".join(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}"/>' for x, y, w, h, rx in bars)

    def letter_shapes(fill):
        return "".join(f"<{tag} {attrs.strip()} fill=\"{fill}\"/>" for tag, attrs in letters)

    standalone = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VB}">'
                  f'<path d="{bubble}" fill="{TEAL}"/>{bar_rects("#fff")}'
                  f'{letter_shapes("#000")}{rects(dots, TEAL)}'
                  f'<path d="{text_d}" fill="#000"/></svg>')
    open(OUT_SVG, "w").write(standalone)

    inline = (f'<svg class="logo-svg" viewBox="{VB}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="DeenSubs">'
              f'<path d="{bubble}" fill="var(--accent)"/>{bar_rects("var(--bg)")}'
              f'{letter_shapes("currentColor")}{rects(dots, "var(--accent)")}'
              f'<path d="{text_d}" fill="currentColor"/></svg>')

    favicon = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">'
               f'<rect width="128" height="128" rx="26" fill="#f6f4ee"/>'
               f'<g transform="translate(25,16) scale(0.3) translate(-404,-22)">'
               f'<path d="{bubble}" fill="{TEAL}"/>{bar_rects("#f6f4ee")}</g></svg>')

    js = ("// GENERATED by tools/logo/build-logo.py — edit src/artifacts/deensubs-src.svg and rerun.\n"
          "// DeenSubs logo lockup — outlined Cairo SemiBold + Arabic + caption bubble.\n"
          "// Theme-aware: text uses currentColor, bubble/dots use var(--accent), bars var(--bg).\n"
          f"export const LOGO_SVG = {json.dumps(inline)};\n\n"
          "// Favicon / PWA icon — bubble mark on a paper tile (light-default brand colors).\n"
          f"export const FAVICON_SVG = {json.dumps(favicon)};\n")
    open(OUT_JS, "w").write(js)
    print(f"wrote {OUT_SVG} ({len(standalone)}b), {OUT_JS} ({len(js)}b)")


if __name__ == "__main__":
    main()
