name = "deensubs"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[rules]]
type = "Text"
globs = ["**/*.css", "**/*.txt"]
fallthrough = false

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "deensubs-media-weur"

[[d1_databases]]
binding = "DB"
database_name = "deensubs-db-weur"
database_id = "e90d776f-5d7a-4b8e-8e3a-3c0b5e9dd0aa"
